# Generated by Django 5.0.4 on 2024-04-17 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("name", models.CharField(max_length=255, verbose_name="Ф. И. О.")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="комментарий"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_mailing_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="время последней рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=50, null=True, verbose_name="статус попытки рассылки"
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="ответ сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог",
                "verbose_name_plural": "логи",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="заголовок рассылки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата начала"
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="последующая дата",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="конечная дата"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("day", "единожды в день"),
                            ("week", "единожды в неделю"),
                            ("month", "единожды в месяц"),
                        ],
                        default="единоразовая",
                        max_length=64,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "Завершено"),
                            ("created", "Создано"),
                            ("launched", "В работе"),
                        ],
                        max_length=64,
                        null=True,
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="актуальная"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("start_date",),
                "permissions": [
                    ("set_is_activated", "Может менять активность рассылки")
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=150, verbose_name="тема")),
                ("body", models.TextField(verbose_name="текст")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщение",
            },
        ),
    ]
